// Auth/user types
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";

export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';

export const CREATE_FIRST_BUDGET = 'CREATE_BUDGET';
export const CREATE_FIRST_BUDGET_SUCCESS = 'CREATE_BUDGET_SUCCESS';
export const CREATE_FIRST_BUDGET_FAILED = 'CREATE_BUDGET_FAILED';


// Budget types
export const GET_BUDGETS = "GET_BUDGETS";
export const GET_BUDGETS_SUCCESS = "GET_BUDGETS_SUCCESS";
export const GET_BUDGETS_FAILURE = "GET_BUDGETS_FAILURE";

export const UPDATE_BUDGET = 'UPDATE_BUDGET';
export const UPDATE_BUDGET_SUCCESS = 'UPDATE_BUDGET_SUCCESS';
export const UPDATE_BUDGET_FAILED = 'UPDATE_BUDGET_FAILED';

export const CREATE_BUDGET = 'CREATE_BUDGET';
export const CREATE_BUDGET_SUCCESS = 'CREATE_BUDGET_SUCCESS';
export const CREATE_BUDGET_FAILED = 'CREATE_BUDGET_FAILED';