// Auth/user types
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";

export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const CREATE_FIRST_BUDGET = 'CREATE_BUDGET';
export const CREATE_FIRST_BUDGET_SUCCESS = 'CREATE_BUDGET_SUCCESS';
export const CREATE_FIRST_BUDGET_FAILURE = 'CREATE_FIRST_BUDGET_FAILURE';


// Budget types
export const GET_BUDGETS = "GET_BUDGETS";
export const GET_BUDGETS_SUCCESS = "GET_BUDGETS_SUCCESS";
export const GET_BUDGETS_FAILURE = "GET_BUDGETS_FAILURE";

export const UPDATE_BUDGET = 'UPDATE_BUDGET';
export const UPDATE_BUDGET_SUCCESS = 'UPDATE_BUDGET_SUCCESS';
export const UPDATE_BUDGET_FAILURE = 'UPDATE_BUDGET_FAILURE';

export const CREATE_BUDGET = 'CREATE_BUDGET';
export const CREATE_BUDGET_SUCCESS = 'CREATE_BUDGET_SUCCESS';
export const CREATE_BUDGET_FAILURE = 'CREATE_BUDGET_FAILURE';

// Item types
export const GET_ITEMS = "GET_BUDGETS";
export const GET_ITEMS_SUCCESS = "GET_BUDGETS_SUCCESS";
export const GET_ITEMS_FAILURE = "GET_BUDGETS_FAILURE";

export const UPDATE_ITEMS = "UPDATE_ITEMS";
export const UPDATE_ITEMS_SUCCESS = "UPDATE_ITEMS_SUCCESS";
export const UPDATE_ITEMS_FAILURE = "UPDATE_ITEMS_FAILURE";

export const GET_PURCHASE_ITEMS = "GET_PURCHASE_ITEMS";
export const GET_PURCHASE_ITEMS_SUCCEESS = "GET_PURCHASE_ITEMS_SUCCEESS";
export const GET_PURCHASE_ITEMS_FAILURE = "GET_PURCHASE_ITEMS_FAILURE";


// Purchase types
export const GET_PURCHASES = "GET_PURCHASES";
export const GET_PURCHASES_SUCCESS = "GET_PURCHASES_SUCCESS";
export const GET_PURCHASES_FAILURE = "GET_PURCHASES_FAILURE";

export const UPDATE_PURCHASES = "UPDATE_PURCHASES";
export const UPDATE_PURCHASES_SUCCESS = "UPDATE_PURCHASES_SUCCESS";
export const UPDATE_PURCHASES_FAILURE = "UPDATE_PURCHASES_FAILURE";